services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: thapeloseema
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5433
      PGDATA: /data/postgres
    ports:
      - "5433:5433"
    volumes:
      - ./postgres:/data/postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - ./pgadmin:/var/lib/pgadmin